=== thousandparsec-obsolete/battleviewer/battle.dtd
<!ELEMENT battle (sides, rounds) >
<!ATTLIST battle version CDATA #REQUIRED >

<!-- Who is in the battle -->
<!ELEMENT sides (side+) >
<!ELEMENT side (entity+) >
<!ATTLIST side id ID #REQUIRED >
<!ELEMENT entity (name, model, description?, deathmedia?, firing?, weapontype?, weapon?, note*) >
<!ATTLIST entity id ID #REQUIRED >
<!ELEMENT name (#PCDATA) >
<!ELEMENT model (#PCDATA) >
<!ELEMENT description (#PCDATA) >
<!ELEMENT deathmedia (#PCDATA) >
<!ELEMENT firing (#PCDATA) >
<!ELEMENT weapontype (#PCDATA) >
<!ELEMENT weaponpoints (pixel)>
	<!ELEMENT pixel (#PCDATA) >
<!ELEMENT weapon (#PCDATA) >
<!ELEMENT note (#PCDATA) >

<!-- What happened in the battle -->
<!ELEMENT rounds (round+) >
<!ELEMENT round (log*, move*, (fire | damage | death)* ) >
<!ATTLIST round number NMTOKEN #REQUIRED >

<!-- Possible actions which can occur -->
<!ELEMENT log (#PCDATA) >
<!ELEMENT move (reference, position) >
<!ELEMENT fire (source, destination) >
<!ELEMENT damage (reference, amount) >
<!ELEMENT death (reference) >

<!-- Arguments for the actions -->
<!ELEMENT reference EMPTY >
<!ATTLIST reference ref IDREF #REQUIRED >
<!ELEMENT position (#PCDATA) >
<!ATTLIST source ref IDREF #REQUIRED >
<!ATTLIST destination ref IDREF #REQUIRED >
<!ELEMENT amount (#PCDATA) >

=== thousandparsec-obsolete/battleviewer/example1.xml
<?xml version="1.0"?>
<!DOCTYPE protocol SYSTEM "battle.dtd">
<battle version="0.0.1">
<sides>
	<side id="mithro">
		<entity id="battleship-54-1">
			<name>Mithro's Super Fleet, Battleship 1</name>
			<model>graphics/battleship/model.mng</model>
			<weapontype>laser5</weapontype>
		</entity>
		<entity id="battleship-54-2">
			<name>Mithro's Super Fleet, Battleship 2</name>
			<model>graphics/battleship/model.mng</model>
			<weapontype>laser5</weapontype>
		</entity>
		<entity id="planet-23">
			<name>Mithro's Colony on Omega 1</name>
			<model>graphics/planet/model.mng</model>
			<weapontype>laser5</weapontype>
		</entity>
	</side>
	<side id="lee">
		<entity id="scout-59-1">
			<name>Lee's Super Fleet, Scout 1</name>
			<model>graphics/scout/model.png</model>
		</entity>
		<entity id="battleship-59-2">
			<name>Lee's Super Fleet, Battleship 1</name>
			<model>graphics/battleship/model.png</model>
			<weapontype>laser5</weapontype>
		</entity>
		<entity id="frigate-59-3">
			<name>Lee's Super Fleet, Frigate 1</name>
			<model>graphics/frigate/model.png</model>
			<weapontype>laser2</weapontype>
		</entity>
	</side>
</sides>
<rounds>
	<round no="1">
		<log>Battle between Lee's Super Fleet and Mithro's killer fleet started.</log>
		<move>
			<reference>battleship-54-1</reference>
			<position>0,0</position>
		</move>
		<move>
			<reference>battleship-54-2</reference>
			<position>100,0</position>
		</move>
		<move>
			<reference>planet-23</reference>
			<position>200,0</position>
		</move>
		<move>
			<reference>scout-59-1</reference>
			<position>0, 400</position>
		</move>
		<move>
			<reference>battleship-59-2</reference>
			<position>100, 400</position>
		</move>
		<move>
			<reference>frigate-59-3</reference>
			<position>200, 400</position>
		</move>
	</round>
	<round no="2">
		<log>Lee's fleet chooses rock.</log>
		<log>Mithro's fleet chooses paper.</log>
		<log>Lee's fleet wins.</log>
		<fire>
			<source>
				<reference>frigate-59-3</reference>
				<pixel>0,0</pixel>
			</source>
			<destination>
				<reference>battleship-54-1</reference>
				<pixel>0,0</pixel>
			</destination>
		</fire>
		<fire>
			<source>
				<reference>battleship-59-2</reference>
				<pixel>0,0</pixel>
			</source>
			<destination>
				<reference>battleship-54-2</reference>
				<pixel>0,0</pixel>
			</destination>
		</fire>
		<damage>
			<reference>battleship-54-1</reference>
			<amount>2</amount>
		</damage>
		<damage>
			<reference>battleship-54-2</reference>
			<amount>3</amount>
		</damage>
	</round>
	<round no="3">
		<log>Lee's fleet chooses rock.</log>
		<log>Mithro's fleet chooses scissors.</log>
		<log>Mithro's fleet wins.</log>
		<fire>
			<source>
				<reference>battleship-54-1</reference>
				<pixel>0,0</pixel>
			</source>
			<destination>
				<reference>battleship-59-1</reference>
				<pixel>0,0</pixel>
			</destination>
		</fire>
		<damage>
			<reference>battleship-59-1</reference>
			<amount>3</amount>
		</damage>
		<fire>
			<source>
				<reference>battleship-54-2</reference>
				<pixel>0,0</pixel>
			</source>
			<destination>
				<reference>battleship-59-1</reference>
				<pixel>0,0</pixel>
			</destination>
		</fire>
		<damage>
			<reference>battleship-59-1</reference>
			<amount>3</amount>
		</damage>
		<death>
			<reference>battleship-59-1</reference>
		</death>
		<fire>
			<source>
				<reference>planet-23</reference>
				<pixel>0,0</pixel>
			</source>
			<destination>
				<reference>frigate-59-3</reference>
				<pixel>0,0</pixel>
			</destination>
		</fire>
		<damage>
			<reference>frigate-59-3</reference>
			<amount>3</amount>
		</damage>
		<fire>
			<source>
				<reference>planet-23</reference>
				<pixel>0,0</pixel>
			</source>
			<destination>
				<reference>frigate-59-3</reference>
				<pixel>0,0</pixel>
			</destination>
		</fire>
		<damage>
			<reference>frigate-59-3</reference>
			<amount>3</amount>
		</damage>
		<death>
			<reference>frigate-59-3</reference>
		</death>
	</round>
	<round id="4">
		<log>Lee's fleet chooses paper.</log>
		<log>Mithro's fleet chooses rock.</log>
		<log>Lee's fleet wins.</log>
		<log>Lee's fleet escapes.</log>
	</round>
</rounds>
</battle>
